run:
  timeout: 3m
  tests: true

linters-settings:
  goimports:
    local-prefixes: zone-index

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
    - bodyclose
    - depguard
    - goimports
    - dupl
  enable-all: false
  disable-all: true
