version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      retries: 120
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672
      - 5672:5672

  acceptor:
    image: acceptor:${VERSION}
    ports:
      - 8080:8080
    environment:
      LOG_LEVEL: DEBUG
      APP_NAME: acceptor
      METRICS_PORT: ":8081"
      PORT: ":8080"
      DATABASE_DSN: "mongodb://mongodb:27017/"
      DATABASE_NAME: emails
      PRODUCER_URL: "amqp://guest:guest@rabbitmq:5672/"
      PRODUCER_EXCHANGE: notifications
      PRODUCER_RETRY_TIMEOUT: "2s"

  sender:
    image: sender:${VERSION}
    environment:
      LOG_LEVEL: DEBUG
      APP_NAME: sender
      METRICS_PORT: ":8082"
      PORT: ":8080"
      DATABASE_DSN: "mongodb://mongodb:27017/"
      DATABASE_NAME: emails
      CONSUMER_CONNECTION_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONSUMER_NOTIFICATIONS_QUEUE_EXCHANGE: notifications
      CONSUMER_NOTIFICATIONS_QUEUE_NAME: sender_email_notifications_queue
      SMTP_USERNAME: "your_google_email"
      SMTP_PASSWORD: "your_password"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: ":587"