version: '3.7'
services:
  acceptor:
    build: ./cmd/acceptor
    #volumes:
    #  - "~/go/src/projects/email-sending-service/config/config.json:app/config/config.json"
    ports:
      - "8080:8080"

  sender:
    build: ./cmd/sender
    image: sender