version: '3.7'
services:
  mongodb:
    image:

  acceptor:
    image: acceptor:latest
    #volumes:
    #  - "~/go/src/projects/email-sending-service/config/config.json:app/config/config.json"
    ports:
      - "8080:8080"

  sender:
    image: sender:latest